import type { Metadata } from 'next'
import Link from "next/link";
import styles from "./page.module.css";
import ROICalculator from "@/app/components/ROICalculator";

export const metadata: Metadata = {
  title: 'AI Chatbots & Automation for Small Business | StrikePath',
  description: 'Done-for-you AI chatbots, receptionists & automation for small business owners. Live in 48 hours. No contracts. Starting at $149/mo.',
  openGraph: {
    title: 'AI Chatbots & Automation for Small Business | StrikePath',
    description: 'Done-for-you AI chatbots, receptionists & automation for small business owners. Live in 48 hours. No contracts. Starting at $149/mo.',
  },
  twitter: {
    title: 'AI Chatbots & Automation for Small Business | StrikePath',
    description: 'Done-for-you AI chatbots, receptionists & automation for small business owners. Live in 48 hours. No contracts. Starting at $149/mo.',
  },
}

const services = [
  {
    icon: "💬",
    name: "AI Chatbot",
    desc: "24/7 customer support and lead capture. Answers FAQs, collects leads, and hands off when needed — without hiring anyone.",
    from: "$149",
    href: "/ai-chatbot-for-small-business",
  },
  {
    icon: "📞",
    name: "AI Receptionist",
    desc: "Answers calls, books appointments, and handles questions every hour of every day. Built on Vapi, synced to your CRM.",
    from: "$349",
    href: "/ai-receptionist-for-small-business",
  },
  {
    icon: "⚙️",
    name: "AI Automation",
    desc: "Connect your tools and eliminate manual work. Workflows that run themselves so your team stays focused on what matters.",
    from: "$197",
    href: "/ai-automation-for-small-business",
  },
  {
    icon: "📣",
    name: "AI Marketing",
    desc: "Fresh ad creatives every month, generated by AI. Stop paying agencies thousands for the same results you can get here.",
    from: "$197",
    href: "/ai-marketing-for-small-business",
  },
];

const steps = [
  {
    num: "01",
    title: "Pick a service",
    desc: "Choose your tier and check out. No sales call, no waiting.",
  },
  {
    num: "02",
    title: "Fill the form",
    desc: "A short onboarding form. Under 5 minutes. That's everything we need.",
  },
  {
    num: "03",
    title: "We build it",
    desc: "Our AI-powered build process starts immediately. No back and forth.",
  },
  {
    num: "04",
    title: "You're live",
    desc: "Your service is delivered within 48 hours. Ready to use from day one.",
  },
];

const whyItems = [
  {
    stat: "48hr",
    label: "Delivery guarantee",
    desc: "Every service delivered within 48 hours of your onboarding form. Not days, not weeks.",
  },
  {
    stat: "$0",
    label: "Setup fees",
    desc: "No setup costs, no contracts, no surprise invoices. One flat monthly rate, cancel anytime.",
  },
  {
    stat: "50",
    label: "States served",
    desc: "Fully remote, coast to coast. Your location has never been a barrier to getting good AI tools.",
  },
];

export default function Home() {
  return (
    <main className={styles.root}>
      {/* ── NAV ── */}
      <nav className={styles.nav}>
        <Link href="/" aria-label="StrikePath — home" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', textDecoration: 'none' }}>
          <img src="/strikepath-logo.png" alt="" aria-hidden="true" style={{ height: '28px', width: 'auto', display: 'block' }} />
          <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 300, fontSize: '0.85rem', letterSpacing: '0.08em', color: 'var(--bone-dim)', lineHeight: 1 }}>StrikePath</span>
        </Link>
        <ul className={styles.navLinks}>
          <li>
            <Link href="/services">Services</Link>
          </li>
          <li>
            <Link href="/#process">How We Work</Link>
          </li>
        </ul>
        <Link href="/services" className={styles.navCta}>
          Get Started
        </Link>
      </nav>

      {/* ── HERO ── */}
      <section className={styles.hero}>
        {/* Background video */}
        <video
          className={styles.heroBg}
          src="/strikepath-hero.mp4"
          autoPlay
          muted
          loop
          playsInline
        />
        <div className={styles.heroOverlay} />

        <div className={styles.heroContent}>
          <h1 className={styles.h1}>
            We Build the AI.<br />
            <em>You Run the Business.</em>
          </h1>

          <p className={styles.heroSub}>
            Done-for-you AI chatbots, automation, receptionists, and marketing
            tools. Delivered within 48 hours.
          </p>

          <div className={styles.heroCtas}>
            <Link href="/services" className={styles.btnPrimary}>
              See Our Services →
            </Link>
            <Link href="/#process" className={styles.btnSecondary}>
              How It Works
            </Link>
          </div>

          <div className={styles.trustRow}>
            <div className={styles.trustItem}>
              <span className={styles.trustDot} />
              Delivered within 48 hours
            </div>
            <div className={styles.trustDivider} />
            <div className={styles.trustItem}>
              <span className={styles.trustDot} />
              No contracts
            </div>
            <div className={styles.trustDivider} />
            <div className={styles.trustItem}>
              <span className={styles.trustDot} />
              Cancel anytime
            </div>
            <div className={styles.trustDivider} />
            <div className={styles.trustItem}>
              <span className={styles.trustDot} />
              All 50 states
            </div>
          </div>
        </div>
      </section>

      {/* ── SERVICES ── */}
      <section className={styles.section} id="services">
        <div className={styles.sectionInner}>
          <p className={styles.sectionLabel}>What we build</p>
          <h2 className={styles.sectionTitle}>
            Four ways to put your<br />business on autopilot.
          </h2>
          <p className={styles.sectionSub}>
            Pick the service that fits. Each one is built, delivered, and
            running within 48 hours.
          </p>

          <div className={styles.serviceGrid}>
            {services.map((s) => (
              <Link key={s.name} href={s.href} className={styles.serviceCard}>
                <div className={styles.serviceIcon}>{s.icon}</div>
                <div className={styles.serviceName}>{s.name}</div>
                <div className={styles.serviceDesc}>{s.desc}</div>
                <div className={styles.servicePrice}>
                  <span className={styles.priceFrom}>from</span>
                  <span className={styles.priceAmt}>{s.from}</span>
                  <span className={styles.pricePeriod}>/mo</span>
                  <span style={{
                    fontFamily: 'var(--font-mono)',
                    fontSize: '9px',
                    fontWeight: 400,
                    letterSpacing: '0.12em',
                    textTransform: 'uppercase',
                    color: 'var(--gold)',
                    border: '1px solid var(--gold)',
                    borderRadius: '3px',
                    padding: '2px 6px',
                    whiteSpace: 'nowrap',
                    lineHeight: 1,
                  }}>Launch Special</span>
                </div>
                <span style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: '0.58rem',
                  fontWeight: 300,
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase',
                  color: 'var(--gold)',
                  paddingTop: '0.25rem',
                }}>Learn more →</span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ── PROCESS ── */}
      <section className={`${styles.section} ${styles.sectionAlt}`} id="process">
        <div className={styles.sectionInner}>
          <p className={styles.sectionLabel}>How it works</p>
          <h2 className={styles.sectionTitle}>Live within 48 hours. Four steps.</h2>

          <div className={styles.stepsGrid}>
            {steps.map((s) => (
              <div key={s.num} className={styles.step}>
                <div className={styles.stepNum}>{s.num}</div>
                <div className={styles.stepTitle}>{s.title}</div>
                <div className={styles.stepDesc}>{s.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── ROI CALCULATOR ── */}
      <section className={styles.section} id="roi">
        <div className={styles.sectionInner}>
          <p className={styles.sectionLabel}>ROI · See Your Savings</p>
          <h2 className={styles.sectionTitle}>
            What is manual work<br />
            <span style={{ color: 'var(--blue)' }}>actually costing you?</span>
          </h2>
          <div style={{ marginTop: '2.5rem' }}>
            <ROICalculator />
          </div>
        </div>
      </section>

      {/* ── WHY ── */}
      <section className={styles.section} id="why">
        <div className={styles.sectionInner}>
          <p className={styles.sectionLabel}>Why StrikePath</p>
          <h2 className={styles.sectionTitle}>
            Not an agency. Not a freelancer.<br />Something faster.
          </h2>
          <p className={styles.sectionSub}>
            Traditional agencies take weeks and charge thousands. We use AI to
            build the same tools in a fraction of the time — at a flat monthly
            rate.
          </p>

          <div className={styles.whyGrid}>
            {whyItems.map((w) => (
              <div key={w.label} className={styles.whyCard}>
                <div className={styles.whyStat}>{w.stat}</div>
                <div className={styles.whyLabel}>{w.label}</div>
                <div className={styles.whyDesc}>{w.desc}</div>
              </div>
            ))}
          </div>
          <p style={{ marginTop: '2rem' }}>
            <Link href="/ai-agency-phoenix-arizona" style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '0.58rem',
              fontWeight: 300,
              letterSpacing: '0.18em',
              textTransform: 'uppercase',
              color: 'var(--gold)',
              textDecoration: 'none',
            }}>Serving Phoenix &amp; Arizona →</Link>
          </p>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className={styles.section} id="faq">
        <div className={styles.sectionInner}>
          <p className={styles.sectionLabel}>Common Questions</p>
          <h2 className={styles.sectionTitle}>Frequently Asked Questions</h2>
          <div style={{ marginTop: '2.5rem', maxWidth: '48rem' }}>
            {([
              { q: 'How fast is delivery?', a: 'Every service is delivered within 48 hours of you submitting the onboarding form. Most clients are live the same day.' },
              { q: 'Are there contracts or setup fees?', a: 'No contracts and no setup fees — ever. You pay month-to-month and can cancel anytime with no penalties.' },
              { q: 'What does it cost?', a: 'Plans start at $149/mo for an AI chatbot. AI receptionists start at $349/mo, automation workflows at $197/mo, and AI marketing at $197/mo. All are flat monthly rates.' },
              { q: 'Do you work with businesses outside Arizona?', a: 'Yes. We serve small businesses in all 50 states. Everything is built and delivered remotely — your location is never a barrier.' },
            ] as { q: string; a: string }[]).map(({ q, a }) => (
              <div key={q} style={{ borderBottom: '1px solid var(--line)', padding: '1.5rem 0' }}>
                <p style={{ fontFamily: 'var(--font-display)', fontWeight: 300, fontSize: 'clamp(0.95rem, 1.4vw, 1.1rem)', color: 'var(--bone)', marginBottom: '0.5rem', letterSpacing: '-0.01em' }}>{q}</p>
                <p style={{ fontFamily: 'var(--font-sans)', fontWeight: 300, fontSize: '0.9375rem', lineHeight: 1.75, color: 'rgba(236,227,204,0.65)' }}>{a}</p>
              </div>
            ))}
          </div>
          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: [
              { '@type': 'Question', name: 'How fast is delivery?', acceptedAnswer: { '@type': 'Answer', text: 'Every service is delivered within 48 hours of you submitting the onboarding form. Most clients are live the same day.' } },
              { '@type': 'Question', name: 'Are there contracts or setup fees?', acceptedAnswer: { '@type': 'Answer', text: 'No contracts and no setup fees — ever. You pay month-to-month and can cancel anytime with no penalties.' } },
              { '@type': 'Question', name: 'What does it cost?', acceptedAnswer: { '@type': 'Answer', text: 'Plans start at $149/mo for an AI chatbot. AI receptionists start at $349/mo, automation workflows at $197/mo, and AI marketing at $197/mo. All are flat monthly rates.' } },
              { '@type': 'Question', name: 'Do you work with businesses outside Arizona?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. We serve small businesses in all 50 states. Everything is built and delivered remotely — your location is never a barrier.' } },
            ],
          }) }} />
        </div>
      </section>

      {/* ── CTA STRIP ── */}
      <section className={`${styles.section} ${styles.sectionAlt} ${styles.ctaSection}`}>
        <div className={styles.sectionInner}>
          <h2 className={styles.ctaTitle}>
            Ready to stop doing work<br />AI can do for you?
          </h2>
          <p className={styles.ctaSub}>
            Starting at $149/mo. No contracts. Delivered within 48 hours.
          </p>
          <Link href="/services" className={styles.btnPrimary}>
            View All Services →
          </Link>
        </div>
      </section>

    </main>
  );
}
